# Generated by Django 5.1.7 on 2025-03-23 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=300)),
                ('state', models.TextField(max_length=300)),
                ('city', models.TextField(max_length=300)),
                ('country', models.TextField(max_length=300)),
                ('pincode', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('openingtime', models.TextField()),
                ('closingtime', models.TextField()),
                ('Status', models.BooleanField(default=False)),
                ('worikingdays', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='OwnersOperations.shopdetails')),
            ],
        ),
    ]
