# Generated by Django 5.1.7 on 2025-03-31 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.TextField()),
                ('address', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('pincode', models.TextField()),
                ('category', models.TextField()),
                ('openingTime', models.TextField()),
                ('closingTime', models.TextField()),
                ('Status', models.BooleanField(default=False)),
                ('shopDaysOpen', models.JSONField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='OwnersOperations.shopdetails')),
            ],
        ),
    ]
