# Generated by Django 5.1.7 on 2025-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnersOperations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='worikingdays',
            field=models.JSONField(null=True),
        ),
    ]
