# Generated by Django 5.1.7 on 2025-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnersOperations', '0002_alter_shopdetails_worikingdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='image',
            field=models.ImageField(null=True, upload_to='shop_images/'),
        ),
    ]
